packages:
  - 'packages/**'

catalogs:
  # Vue框架核心及周边
  vue:
    "vue": "^3.5.13"
    "vue-router": "^4.5.0"
    "@vue/compiler-sfc": "^3.5.17"
    "@vue/compiler-dom": "^3.5.17"
    "pinia": "^3.0.3"
    "@vitejs/plugin-vue": "^5.2.1"
    "vue-component-meta": "^2.2.10"
    "vue-docgen-api": "^4.79.2"

  # Markdown处理
  markdown:
    "markdown-it": "^14.1.0"
    "markdown-it-async": "^2.2.0"
    "unplugin-vue-markdown": "^28.3.1"
    "gray-matter": "^4.0.3"
    "@shikijs/langs": "^3.7.0"
    "@shikijs/themes": "^3.7.0"
    "shiki": "^3.7.0"

  # CSS与样式处理
  css:
    "clean-css": "^5.3.3"
    "normalize.css": "^8.0.1"
    "sass-embedded": "^1.83.4"
    "sass": "^1.71.1"

  # 构建工具
  build:
    "vite": "^6.2.3"
    "vite-plugin-dts": "^4.5.3"
    "vue-tsc": "2.2.8"
    "@rollup/plugin-terser": "^0.4.4"
    "vite-plugin-inspect": "^11.2.0"
    "svgo": "^3.3.2"

  # TypeScript相关
  typescript:
    "typescript": "~5.8.2"
    "@types/node": "^22.13.1"
    "@types/clean-css": "^4.2.11"
    "@types/fs-extra": "^9.0.13"
    "@types/glob": "^8.1.0"
    "@types/markdown-it": "^14.1.0"

  # 代码质量工具
  lint:
    "eslint": "^8.57.1"
    "eslint-plugin-vue": "^9.32.0"
    "vue-eslint-parser": "^10.2.0"
    "@vue/eslint-config-typescript": "^12.0.0"
    "@rushstack/eslint-patch": "^1.10.5"
    "prettier": "^3.6.2"

  # io工具
  io:
    "glob": "^11.0.1"
    "fs-extra": "^11.3.0"
    "commander": "^13.1.0"

  # 其余工具
  utils:
    "magic-string": "^0.30.17"
    "@opensig/open-analytics": "0.0.3"
    "vite-node": "^3.2.4"
