packages:
  - 'packages/**'

catalog:
  # dependencies
  "vue": "^3.5.13"
  "vue-router": "^4.5.0"
  "clean-css": "^5.3.3"
  "glob": "^11.0.1"
  "sass-embedded": "^1.83.4"
  "sass": "^1.71.1"
  "svgo": "^3.3.2"
  "date-fns": "^2.30.0"
  "normalize.css": "^8.0.1"

  # devDependencies
  "typescript": "~5.8.2"
  "commander": "^13.1.0"
  "fs-extra": "^11.3.0"
  "@opensig/open-analytics": "0.0.3"

  "vite": "^6.2.3"
  "vue-tsc": "2.2.8"
  "@rollup/plugin-terser": "^0.4.4"
  "@vitejs/plugin-vue": "^5.2.1"
  "vite-plugin-dts": "^4.5.3"

  "eslint": "^8.57.1"
  "eslint-plugin-vue": "^9.32.0"
  "@vue/eslint-config-typescript": "^12.0.0"
  "@rushstack/eslint-patch": "^1.10.5"

  "@types/node": "^22.13.1"
  "@types/clean-css": "^4.2.11"
  "@types/fs-extra": "^9.0.13"
  "@types/glob": "^8.1.0"
  "unplugin-vue-markdown": "^28.3.1"
  "vite-plugin-inspect": "^11.2.0"
  "highlight.js": "^11.11.1"
  "gray-matter": "^4.0.3"
  "markdown-it-async": "^2.2.0"
  "@vue/compiler-sfc": "^3.5.17"
  "markdown-it": "^14.1.0"
  "@types/markdown-it": "^14.1.0"
  "magic-string": "^0.30.17"
  "vue-component-meta": "^2.2.10"
  "vue-docgen-api": "^4.79.2"
  "prettier": "^3.6.2"
  "pinia": "^3.0.3"
