packages:
  - packages/**

catalogs:
  build:
    '@rollup/plugin-terser': ^0.4.4
    svgo: ^3.3.2
    vite: ^6.2.3
    vite-plugin-dts: ^4.5.3
    vite-plugin-inspect: ^11.2.0
    vue-tsc: 2.2.8
    '@opensig/open-scripts': 1.0.0
  css:
    clean-css: ^5.3.3
    normalize.css: ^8.0.1
    sass: ^1.71.1
    sass-embedded: 1.85.1
  io:
    commander: ^13.1.0
    fs-extra: ^11.3.0
    glob: ^11.0.1
  lint:
    eslint: ^9.39.1
    eslint-plugin-vue: ^10.6.1
    "typescript-eslint": "^8.48.0"
    "globals": "^16.5.0"
    "@eslint/js": "^9.39.1"
    prettier: ^3.6.2
    "eslint-config-prettier": "^10.1.8"

  markdown:
    '@shikijs/langs': ^3.7.0
    '@shikijs/themes': ^3.7.0
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-async: ^2.2.0
    shiki: ^3.7.0
    unplugin-vue-markdown: ^28.3.1
  typescript:
    '@types/clean-css': ^4.2.11
    '@types/fs-extra': ^9.0.13
    '@types/glob': ^8.1.0
    '@types/markdown-it': ^14.1.0
    '@types/node': ^22.19.1
    ts-morph: ^27.0.2
    typescript: ~5.8.3
  utils:
    '@opensig/open-analytics': 0.0.3
    magic-string: ^0.30.17
    vite-node: ^3.2.4
  vue:
    '@vitejs/plugin-vue': ^6.0.2
    '@vue/compiler-dom': ^3.5.17
    '@vue/compiler-sfc': ^3.5.17
    pinia: ^3.0.3
    vue: ^3.5.25
    vue-component-meta: ^2.2.10
    vue-docgen-api: ^4.79.2
    vue-router: ^4.6.3
