server {
    listen       8080;
    server_name  0.0.0.0;
    root         /usr/share/nginx/www;

    location ~ ^/(\d[^/]+)(/.*)?$ {
      if (!-d $document_root/$1) {
        return 404;
      }

      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        add_header Cache-Control "public, max-age=2592000";
        expires 30d;
      }

      index index.html index.htm;
      try_files $uri $uri/ /$1/index.html;
    }

    location / {
      rewrite ^/(.*)$ /${LATEST_VERSION}/$1 last;
    }
}

